/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jdmp.core.script.jdmp.node;

import org.jdmp.core.script.jdmp.analysis.Analysis;

@SuppressWarnings("nls")
public final class TBitComplement extends Token {
	public TBitComplement() {
		super.setText("~");
	}

	public TBitComplement(int line, int pos) {
		super.setText("~");
		setLine(line);
		setPos(pos);
	}

	public Object clone() {
		return new TBitComplement(getLine(), getPos());
	}

	public void apply(Switch sw) {
		((Analysis) sw).caseTBitComplement(this);
	}

	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TBitComplement text.");
	}
}
