/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jdmp.core.script.jdmp.node;

import org.jdmp.core.script.jdmp.analysis.Analysis;

@SuppressWarnings("nls")
public final class TLogicalAnd extends Token {
	public TLogicalAnd() {
		super.setText("&&");
	}

	public TLogicalAnd(int line, int pos) {
		super.setText("&&");
		setLine(line);
		setPos(pos);
	}

	public Object clone() {
		return new TLogicalAnd(getLine(), getPos());
	}

	public void apply(Switch sw) {
		((Analysis) sw).caseTLogicalAnd(this);
	}

	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TLogicalAnd text.");
	}
}
