/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jdmp.core.script.jdmp.node;

import org.jdmp.core.script.jdmp.analysis.Analysis;

@SuppressWarnings("nls")
public final class TLteq extends Token {
	public TLteq() {
		super.setText("<=");
	}

	public TLteq(int line, int pos) {
		super.setText("<=");
		setLine(line);
		setPos(pos);
	}

	public Object clone() {
		return new TLteq(getLine(), getPos());
	}

	public void apply(Switch sw) {
		((Analysis) sw).caseTLteq(this);
	}

	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TLteq text.");
	}
}
