/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jdmp.core.grammar.jdmp.parser;

import org.jdmp.core.grammar.jdmp.node.*;
import org.jdmp.core.grammar.jdmp.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTSemicolonToken(@SuppressWarnings("unused") TSemicolonToken node)
    {
        this.index = 0;
    }

    @Override
    public void caseTPlusToken(@SuppressWarnings("unused") TPlusToken node)
    {
        this.index = 1;
    }

    @Override
    public void caseTMinusToken(@SuppressWarnings("unused") TMinusToken node)
    {
        this.index = 2;
    }

    @Override
    public void caseTMultiplicationToken(@SuppressWarnings("unused") TMultiplicationToken node)
    {
        this.index = 3;
    }

    @Override
    public void caseTDivisionToken(@SuppressWarnings("unused") TDivisionToken node)
    {
        this.index = 4;
    }

    @Override
    public void caseTCommaToken(@SuppressWarnings("unused") TCommaToken node)
    {
        this.index = 5;
    }

    @Override
    public void caseTEqualsToken(@SuppressWarnings("unused") TEqualsToken node)
    {
        this.index = 6;
    }

    @Override
    public void caseTLParToken(@SuppressWarnings("unused") TLParToken node)
    {
        this.index = 7;
    }

    @Override
    public void caseTRParToken(@SuppressWarnings("unused") TRParToken node)
    {
        this.index = 8;
    }

    @Override
    public void caseTLBracketToken(@SuppressWarnings("unused") TLBracketToken node)
    {
        this.index = 9;
    }

    @Override
    public void caseTRBracketToken(@SuppressWarnings("unused") TRBracketToken node)
    {
        this.index = 10;
    }

    @Override
    public void caseTNullToken(@SuppressWarnings("unused") TNullToken node)
    {
        this.index = 11;
    }

    @Override
    public void caseTNewToken(@SuppressWarnings("unused") TNewToken node)
    {
        this.index = 12;
    }

    @Override
    public void caseTTrueToken(@SuppressWarnings("unused") TTrueToken node)
    {
        this.index = 13;
    }

    @Override
    public void caseTFalseToken(@SuppressWarnings("unused") TFalseToken node)
    {
        this.index = 14;
    }

    @Override
    public void caseTIdentifierToken(@SuppressWarnings("unused") TIdentifierToken node)
    {
        this.index = 15;
    }

    @Override
    public void caseTIntegerToken(@SuppressWarnings("unused") TIntegerToken node)
    {
        this.index = 16;
    }

    @Override
    public void caseTFloatingPointToken(@SuppressWarnings("unused") TFloatingPointToken node)
    {
        this.index = 17;
    }

    @Override
    public void caseTBooleanToken(@SuppressWarnings("unused") TBooleanToken node)
    {
        this.index = 18;
    }

    @Override
    public void caseTCharacterToken(@SuppressWarnings("unused") TCharacterToken node)
    {
        this.index = 19;
    }

    @Override
    public void caseTStringToken(@SuppressWarnings("unused") TStringToken node)
    {
        this.index = 20;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 21;
    }
}
