/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jdmp.core.script.jdmp.node;

import org.jdmp.core.script.jdmp.analysis.*;

@SuppressWarnings("nls")
public final class AMinusLevel4 extends PLevel4
{
    private PLevel4 _left_;
    private TMinus _minus_;
    private PLevel3 _right_;

    public AMinusLevel4()
    {
        // Constructor
    }

    public AMinusLevel4(
        @SuppressWarnings("hiding") PLevel4 _left_,
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PLevel3 _right_)
    {
        // Constructor
        setLeft(_left_);

        setMinus(_minus_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AMinusLevel4(
            cloneNode(this._left_),
            cloneNode(this._minus_),
            cloneNode(this._right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusLevel4(this);
    }

    public PLevel4 getLeft()
    {
        return this._left_;
    }

    public void setLeft(PLevel4 node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PLevel3 getRight()
    {
        return this._right_;
    }

    public void setRight(PLevel3 node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._minus_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PLevel4) newChild);
            return;
        }

        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PLevel3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
