/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jdmp.core.grammar.jdmp.node;

import org.jdmp.core.grammar.jdmp.analysis.*;

@SuppressWarnings("nls")
public final class AFalse extends PFalse
{
    private TFalseToken _falseToken_;

    public AFalse()
    {
        // Constructor
    }

    public AFalse(
        @SuppressWarnings("hiding") TFalseToken _falseToken_)
    {
        // Constructor
        setFalseToken(_falseToken_);

    }

    @Override
    public Object clone()
    {
        return new AFalse(
            cloneNode(this._falseToken_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFalse(this);
    }

    public TFalseToken getFalseToken()
    {
        return this._falseToken_;
    }

    public void setFalseToken(TFalseToken node)
    {
        if(this._falseToken_ != null)
        {
            this._falseToken_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._falseToken_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._falseToken_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._falseToken_ == child)
        {
            this._falseToken_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._falseToken_ == oldChild)
        {
            setFalseToken((TFalseToken) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
